### ISSUE TITLE
Remove get_underlying

### ISSUE THREAD

**Issue by jbcoe** [jbcoe/propagate_const#4]

**Comment by aloisklink** [comment]
Is there any reason why `get_underlying` has been removed?

I know there are some discussions like https://groups.google.com/a/isocpp.org/g/std-proposals/c/pqGBkyB2xAI/m/0KcEDxtQAgAJ saying that `get_underlying` isn't useful, but both the
  - [C++ standard libraries extensions, version 2 ISO/IEC TS 19568:2017](https://en.cppreference.com/w/cpp/experimental/lib_extensions_2) and the
  - [N4948 draft from 2023-05-08 for C++ Extensions for Library Fundamentals, Version 3](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/n4948.html#propagate_const.underlying)

seems to contain this `get_underlying` function.

---

As a side-note, thanks for pushing forwards this feature! I'm a big fan of it!

**Comment by jbcoe** [comment]
We think we have a better solution in https://github.com/jbcoe/value_types

Please see if these improved class templates solve the same problem that you were using propagate_const for.
